CREATE DATABASE IF NOT EXISTS reto;
USE reto;
CREATE TABLE IF NOT EXISTS usuario (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(255) NOT NULL,
telefono VARCHAR(30) NOT NULL,
correo VARCHAR(255) NOT NULL,
compania VARCHAR(255) NOT NULL,
calle VARCHAR(255) NOT NULL,
latitud DECIMAL(10, 8) NOT NULL,
longitud DECIMAL(11, 8) NOT NULL
);